### ISSUE TITLE
Смещенные вправо позиции фрагментов

### ISSUE THREAD

**Issue by Koziev** [dialogue-evaluation/AGRR-2019#1]
В dev.csv есть запись (строка 2698)

> Тогда одни посчитали это блефом, другие шантажом, но это был не блеф и не шантаж, мы просто их проинформировали, а они сделали свой выбор, - констатировал он.	1	12:21	7:11	26:32	41:41	34:40	41:49

Фрагмент 12:21 получается "осчитали ", то есть смещен вправо на 1.

Аналогично в файле train.csv запись в строке 1239:

> Учитель, я хочу путешествовать. Но одна часть меня хочет отправиться на запад, а другая на восток. Как мне быть?	1	52:57	36:51	70:78	89:89	82:88	89:98

и т.д.

**Comment by MashaPo** [comment]
да, действительно в некоторых текстах есть проблема со смещенными оффсетами. спасибо! обновим данные и выложим в ближайшее время
