### ISSUE TITLE
Ошибка со смещениями в датасете

### ISSUE THREAD

**Issue by OmelchenkoVladimir** [dialogue-evaluation/AGRR-2019#3]
Похоже, что предыдущая ошибка со смещениями была исправлена не до конца: в train'е и dev'е по-прежнему остались примеры со смещённой разметкой (в train'е - примеры под номерами 1237,  2297,  4778,  5273,  5345,  6301,  7961,  8400,  9672, 10115, 10398, 11680, 13047, 13747, 13787, 14008, 14952, 16321; в dev'е - примеры под номерами 2696, 3022, 4011).

**Comment by MashaPo** [comment]
Если вы загружаете датасет с помощью Pandas, убедитесь, что при загрузке кавычки, содержащиеся в текстах, не удаляются и не экранируются и текст загружается в неизменном виде. Для этого можно использовать параметр  quoting:

>import pandas as pd
>import csv
>dev = pd.read_csv('dev.csv', sep = '\t', quoting=csv.QUOTE_NONE)
