### ISSUE TITLE
[Bug] Скрипт валидации

### ISSUE THREAD

**Issue by ivbelkin** [dialogue-evaluation/AGRR-2019#4]
Функция `symbol_wize` в скрипте `agrr_metrics.py` содержит следующий код:
```python
if y_true1 == y_pred1:
    return 1
```
Ее наличие понятно с точки зрения оптимизации, но и без нее должно все работать. Однако же нет, попытка подсчитать метрики запуском `python3 agrr_metrics.py train.csv train.csv` завершается ошибкой деления на 0. Ровно как и запуск для файла `dev.csv`. Фиксится стандартно, добавлением `eps=1e-7` везде где может проити деление на 0, при этом в числителе тоже ноль. Также по коду видно, и это вылазит после фикса деления на 0, что некорректно обрабатывается случай вроде такого: `V='109:109 147:147'`, это из строки 118 фаила `train.csv`. То есть метрики считаются текущей версией скрипта неверно.

**Comment by TatianaShavrina** [comment]
Можете, пожалуйста, конкретизировать, что именно в метрике будет методологически неверным при текущем скрипте?
Не очень понятно, не как попрпавить, а что по-вашему не так.

**Comment by ivbelkin** [comment]
Скрипт не обрабатывает ситуацию, если в некотором предложении одному тегу, к примеру `V`, соответствует несколько непересакающихся вхождений. Пример такой ситуации - строка 118 фаила `train.csv`. В такой ситуации скрипт просто падает, если отсутствует явное сравнение строк на равенство, которое недопустимо

**Comment by TatianaShavrina** [comment]
Спасибо, поняли!

Сегодня поправим

**Comment by TatianaShavrina** [comment]
fixed in https://github.com/dialogue-evaluation/AGRR-2019/commit/8062355a87ef908400a674067429fcf12a0f17f1
