### ISSUE TITLE
Скрипт валидации

### ISSUE THREAD

**Issue by ivbelkin** [dialogue-evaluation/AGRR-2019#5]
У нас есть три задачи: 

1. Binary presence-absence classification

2. Gap resolution

3. Full annotation

В документации к скрипту указано:
```
Если вы выполняете задание только по gap resolution, укажите -r
```
При этом, указание этого флага приводит к расчету метрик для задачи full annotation. И наоборот, его отсутствие к gap resolution.

И еще один момент. Не все предложения класса 1 содержат все теги (например строка 15 фаила train.csv). В этом случае при чтении вместо пропуска вставляется `int(0)` вызовом `fillna`. При этом функция `symbol_wise` ожидает наличие метода `split()` у объекта, который в данном случае оказывается типа `int`, что приводит к падению скрипта на валидном входе. (кажется, можно `fillna("")`) 

Вылавливание таких ошибок затруднено наличием строк `53:54` в скрипте. Я понимаю, что это ускоряет его работу, но оч прошу их выпилить.

**Comment by TatianaShavrina** [comment]
А Зачем вы делаете fillna(0) ?
Сдавать в таком формате выборку точно не надо, это не conllu-like

Если Вы пользуетесь пандасом, то лучший вариант:
`dev = pd.read_csv('dev.csv', sep = '\t', quoting = csv.QUOTE_NONE) `

**Comment by ivbelkin** [comment]
Это делаю не я, а скрипт валидации. Строка 97 фаила agrr_metrics.py.

**Comment by TatianaShavrina** [comment]
Спасибо! выпилим

**Comment by TatianaShavrina** [comment]
https://github.com/dialogue-evaluation/AGRR-2019/commit/7ca46d3e9a7f23f6b7edee68743a75007e0b456e
